name: yoinn_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_maps_flutter: ^2.14.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  uuid: ^4.5.2
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  go_router: ^17.0.1
  google_sign_in: ^5.4.4
  image_picker: ^1.2.1
  firebase_storage: ^13.0.4
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.6.0
  cached_network_image: ^3.4.1
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  badges: ^3.1.2
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3
  
  # --- PAGOS Y SUSCRIPCIONES ---
  purchases_flutter: ^8.0.0
  purchases_ui_flutter: ^8.0.0
  firebase_analytics: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

# --- CONFIGURACIÓN DE ÍCONOS AUTOMÁTICOS ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/pin_solid.png" # Asegúrate de que esta imagen exista
  min_sdk_android: 21
  remove_alpha_ios: true