name: yoinn_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  
  # --- UI & UTILIDADES ---
  flutter_localizations:
    sdk: flutter
  
  intl: ^0.20.2
  
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  uuid: ^4.4.0
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  go_router: ^14.0.0
  badges: ^3.1.2
  http: ^1.2.1
  rxdart: ^0.28.0 

  # --- FIREBASE ---
  firebase_core: ^3.6.0  
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4 
  firebase_storage: ^12.3.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3

  # --- MAPAS Y UBICACIÓN ---
  google_maps_flutter: ^2.10.0
  custom_info_window: ^1.0.1 # <--- LIBRERÍA AGREGADA
  geolocator: ^13.0.1 
  geocoding: ^3.0.0
  geoflutterfire_plus: ^0.0.26 

  # --- AUTENTICACIÓN SOCIAL ---
  google_sign_in: 6.2.1
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.3

  # --- MEDIOS ---
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # --- NOTIFICACIONES ---
  flutter_local_notifications: ^17.2.3

  # --- PAGOS Y SUSCRIPCIONES ---
  purchases_flutter: ^8.3.0 
  purchases_ui_flutter: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/

# --- CONFIGURACIÓN DE ÍCONOS AUTOMÁTICOS ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/pin_solid.png"
  min_sdk_android: 21
  remove_alpha_ios: true